---
output: revealjs::revealjs_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE) 
options(scipen=999)
library(rmarkdown)
library(flexdashboard)
library(pipeR)
library(tidyverse)
library(rio)
library(ggraph)
library(tidygraph)
library(DT)
library(visNetwork)
library(igraph)
library(highcharter)
library(htmlwidgets)
library(printr)
library(shiny)
library(kableExtra)
```

## 1985

```{r, echo=F, }
netcoup <- import('../data/netcoup.rds') 
hubs <- import('../data/netcoup_hubs.rds') 

hubs %>>% 
    select(SR,Ki) %>>% 
    (. -> hubs2)

netcoup %>>% 
    activate(nodes) %>>% 
    left_join(hubs2) %>>% 
    mutate(label_short=name) %>>% 
    mutate(label_short=paste( gsub(' .*$','',label_short), gsub('.*\\.','',label_short), sep='' )) %>>% 
    dplyr::filter(!is.na(grupo)) %>>% 
    (. -> netcoup2)

## 1985
netcoup2 %>>% 
    dplyr::filter(PY < 1985) %>>% 
    (. -> netcoup3)

V(netcoup3)$group <- cluster_louvain(netcoup3)$membership

ggraph(netcoup3, layout = 'fr') +
    geom_edge_link(aes(alpha = stat(index)), show.legend = F) +
    geom_node_point(aes(size=centrality_degree(), color = group), show.legend=F) + 
    geom_node_text(aes(label = label_short), repel=TRUE)
```

## 1990

```{r, echo=F, }

## 1990
netcoup2 %>>% 
    dplyr::filter(PY < 1990) %>>% 
    (. -> netcoup3)

V(netcoup3)$group <- cluster_louvain(netcoup3)$membership

ggraph(netcoup3, layout = 'fr') +
    geom_edge_link(aes(alpha = stat(index)), show.legend = F) +
    geom_node_point(aes(size=centrality_degree(), color = group), show.legend=F) 
```

## 1995

```{r}

gr <- create_notable('zachary') %>%
  mutate(group = group_infomap()) %>%
  morph(to_split, group) %>%
  activate(edges) %>%
  mutate(edge_group = as.character(.N()$group[1])) %>%
  unmorph()

ggraph(gr, 'matrix', sort.by = node_rank_hclust()) +
  geom_edge_point(aes(colour = edge_group), mirror = TRUE, edge_size = 3, show.legend=F) +
  scale_y_reverse() +
  coord_fixed() 
```

