---
title: "Networks"
author: "Use arrow keys or space to navigate between networks"
date: "Use mouse scrool to zoom-in and zoom-out inside networks"
output: slidy_presentation
---

```{r setup_slide, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(rio)
library(tidyverse)
library(pipeR)
library(tidygraph)
library(visNetwork)
library(igraph)
```

##

```{r echo=F, warning=F, message=F}

netcoup <- import('../data/netcoup.rds') 
hubs <- import('../data/netcoup_hubs.rds') 

hubs %>>% 
    select(SR,Ki) %>>% 
    (. -> hubs2)

netcoup %>>% 
    activate(nodes) %>>% 
    left_join(hubs2) %>>% 
    (. -> netcoup)

netcoup %>>% 
    as_tbl_graph() %>>% 
    activate(nodes) %>>% 
    mutate(label=name) %>>% 
    mutate(label=paste( gsub(' .*$','',label), gsub('.*\\.','',label), sep='' )) %>>% 
    dplyr::filter(!is.na(grupo)) %>>% 
    dplyr::filter(PY <= 1985) %>>% 
    (. -> netcoup2)

tibble(id=1:length(V(netcoup2)),
       label= V(netcoup2)$label,
       group=V(netcoup2)$grupo,
       year=V(netcoup2)$PY
       ) %>>% 
(. -> nodes)

tibble(from = netcoup2 %>>% activate(edges) %>>% as_tibble %>>%  pull(from),
       to = netcoup2 %>>% activate(edges) %>>% as_tibble %>>%  pull(to)
       ) %>>% 
(. -> edges)

visNetwork(nodes, edges, height = "700px", width = "700px", main = as.character(max(V(netcoup2)$PY))) %>%
    visNodes(size = 10) %>>% 
    visEdges(width = 2, hidden=F)  %>>% 
    visOptions(selectedBy = "group", highlightNearest = TRUE, nodesIdSelection = F) %>>%  
    visPhysics(stabilization = T) %>>% 
    visGroups(groupname = "g01", color = "#38501e") %>>% 
    visGroups(groupname = "g02", color = "#23331e") %>>% 
    visGroups(groupname = "g03", color = "#6e1d21") %>>% 
    visGroups(groupname = "g04", color = "#472926") %>>% 
    visGroups(groupname = "g05", color = "#926433") %>>% 
    visGroups(groupname = "g06", color = "#a90a26") %>>% 
    visGroups(groupname = "g07", color = "#97863e") %>>% 
    visGroups(groupname = "g08", color = "#00FFFF") %>>% 
    visGroups(groupname = "g09", color = "#d48d01") %>>% 
    visGroups(groupname = "g10", color = "#021338") %>>% 
    visGroups(groupname = "g11", color = "#e6d82e") %>>% 
    visGroups(groupname = "g12", color = "#9eb739") %>>% 
    visGroups(groupname = "g13", color = "#808080") 
```

##

```{r echo=F, warning=F, message=F}

netcoup %>>% 
    as_tbl_graph() %>>% 
    activate(nodes) %>>% 
    mutate(label=name) %>>% 
    mutate(label=paste( gsub(' .*$','',label), gsub('.*\\.','',label), sep='' )) %>>% 
    dplyr::filter(!is.na(grupo)) %>>% 
    dplyr::filter(PY <= 1990) %>>% 
    (. -> netcoup2)

tibble(id=1:length(V(netcoup2)),
       label= V(netcoup2)$label,
       group=V(netcoup2)$grupo,
       year=V(netcoup2)$PY
       ) %>>% 
(. -> nodes)

tibble(from = netcoup2 %>>% activate(edges) %>>% as_tibble %>>%  pull(from),
       to = netcoup2 %>>% activate(edges) %>>% as_tibble %>>%  pull(to)
       ) %>>% 
(. -> edges)

visNetwork(nodes, edges, height = "700px", width = "700px", main = as.character(max(V(netcoup2)$PY))) %>%
    visNodes(size = 10) %>>% 
    visEdges(width = 2, hidden=F)  %>>% 
    visOptions(selectedBy = "group", highlightNearest = TRUE, nodesIdSelection = F) %>>%  
    visPhysics(stabilization = T) %>>% 
    visGroups(groupname = "g01", color = "#38501e") %>>% 
    visGroups(groupname = "g02", color = "#23331e") %>>% 
    visGroups(groupname = "g03", color = "#6e1d21") %>>% 
    visGroups(groupname = "g04", color = "#472926") %>>% 
    visGroups(groupname = "g05", color = "#926433") %>>% 
    visGroups(groupname = "g06", color = "#a90a26") %>>% 
    visGroups(groupname = "g07", color = "#97863e") %>>% 
    visGroups(groupname = "g08", color = "#00FFFF") %>>% 
    visGroups(groupname = "g09", color = "#d48d01") %>>% 
    visGroups(groupname = "g10", color = "#021338") %>>% 
    visGroups(groupname = "g11", color = "#e6d82e") %>>% 
    visGroups(groupname = "g12", color = "#9eb739") %>>% 
    visGroups(groupname = "g13", color = "#808080") 
```

